vim.cmd("set expandtab")
vim.cmd("set tabstop=4")
vim.cmd("set softtabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("set colorcolumn=80")
vim.cmd("set numberwidth=2")
vim.cmd("set number")
vim.cmd("augroup numbertoggle")
vim.cmd("autocmd!")
vim.cmd("autocmd BufEnter,FocusGained,InsertLeave,WinEnter * if &nu && mode() != 'i' | set rnu   | endif")
vim.cmd("autocmd BufLeave,FocusLost,InsertEnter,WinLeave   * if &nu  | set nornu | endif")
vim.opt.fillchars = {eob = " "}
vim.cmd("augroup END")
vim.keymap.set('n', '<C-n>', ':tabn<CR>', {})
vim.keymap.set('n', '<C-p>', ':tabp<CR>', {})
vim.keymap.set('n', '<C-t>', ':tabnew<CR>', {})
vim.keymap.set('n', '<C-x>', ':tabc<CR>', {})
vim.keymap.set('n', '<C-h>', '<C-w>h', {})
vim.keymap.set('n', '<C-l>', '<C-w>l', {})
vim.keymap.set('n', '<C-j>', '<C-w>j', {})
vim.keymap.set('n', '<C-k>', '<C-w>k', {})
vim.keymap.set('n', '<C-]>', '<C-w>>', {})
vim.keymap.set('n', '<C-[>', '<C-w><', {})
vim.keymap.set('n', '<C-+>', '<C-w>+', {})
vim.keymap.set('n', '<C-_>', '<C-w>-', {})
vim.g.mapleader = " "
